#include "decision_tree.hpp"

// Generated by scripts/train_own_decision_tree.py.
// Source data: /tmp/reference-oracle-65536-jitter-cont.tsv
// Training samples: 65536
// Non-abstain training errors: 0
// max_depth=18 min_leaf=64 max_nodes=8191
// abstain_min_purity=1.0 abstain_min_samples=64
// oracle_target=approval oracle_split_target=count oracle_force_abstain_counts=2,3
// decision_min_margin=0.005

static constexpr float kTreeDecisionMinMargin = 0.005f;

const tree_node_t tree_nodes[] = {
    { 2, 0.0672309474f, 1, 2, 254 },
    { 255, 0.0f, -1, -1, 0 },
    { 3, 0.282658786f, 3, 8, 254 },
    { 13, 0.0115413885f, 4, 7, 254 },
    { 5, 0.00772184087f, 5, 6, 254 },
    { 255, 0.0f, -1, -1, 5 },
    { 255, 0.0f, -1, -1, 254 },
    { 255, 0.0f, -1, -1, 254 },
    { 0, 0.131006666f, 9, 28, 254 },
    { 7, 0.0713974387f, 10, 11, 254 },
    { 255, 0.0f, -1, -1, 254 },
    { 8, 0.500248015f, 12, 25, 254 },
    { 16, 192.881787f, 13, 16, 254 },
    { 11, 0.00123485562f, 14, 15, 254 },
    { 255, 0.0f, -1, -1, 254 },
    { 255, 0.0f, -1, -1, 254 },
    { 6, 0.214496717f, 17, 24, 254 },
    { 16, 432.743843f, 18, 23, 254 },
    { 3, 0.781369358f, 19, 22, 254 },
    { 2, 0.232696228f, 20, 21, 254 },
    { 255, 0.0f, -1, -1, 254 },
    { 255, 0.0f, -1, -1, 254 },
    { 255, 0.0f, -1, -1, 254 },
    { 255, 0.0f, -1, -1, 254 },
    { 255, 0.0f, -1, -1, 254 },
    { 0, 0.0858344733f, 26, 27, 254 },
    { 255, 0.0f, -1, -1, 254 },
    { 255, 0.0f, -1, -1, 254 },
    { 6, 0.232716128f, 29, 58, 254 },
    { 5, 0.0271576112f, 30, 43, 254 },
    { 11, 0.00038566321f, 31, 36, 254 },
    { 2, 0.579144031f, 32, 33, 254 },
    { 255, 0.0f, -1, -1, 254 },
    { 7, 0.222419679f, 34, 35, 254 },
    { 255, 0.0f, -1, -1, 254 },
    { 255, 0.0f, -1, -1, 254 },
    { 3, 0.434864998f, 37, 38, 254 },
    { 255, 0.0f, -1, -1, 254 },
    { 3, 0.825428963f, 39, 42, 254 },
    { 16, 308.9426f, 40, 41, 254 },
    { 255, 0.0f, -1, -1, 254 },
    { 255, 0.0f, -1, -1, 254 },
    { 255, 0.0f, -1, -1, 254 },
    { 5, 0.0340531301f, 44, 45, 254 },
    { 255, 0.0f, -1, -1, 254 },
    { 8, 0.299687431f, 46, 49, 254 },
    { 3, 0.566595465f, 47, 48, 254 },
    { 255, 0.0f, -1, -1, 254 },
    { 255, 0.0f, -1, -1, 254 },
    { 11, 0.999851823f, 50, 55, 254 },
    { 7, 0.140149377f, 51, 52, 254 },
    { 255, 0.0f, -1, -1, 254 },
    { 9, 0.999280095f, 53, 54, 254 },
    { 255, 0.0f, -1, -1, 254 },
    { 255, 0.0f, -1, -1, 254 },
    { 9, 0.00141035201f, 56, 57, 254 },
    { 255, 0.0f, -1, -1, 254 },
    { 255, 0.0f, -1, -1, 254 },
    { 8, 0.301247149f, 59, 60, 254 },
    { 255, 0.0f, -1, -1, 254 },
    { 6, 0.256295279f, 61, 62, 254 },
    { 255, 0.0f, -1, -1, 254 },
    { 255, 0.0f, -1, -1, 254 },
};
const unsigned tree_node_count = 63;

int tree_predict_score(const float features[TREE_FEATURE_COUNT])
{
    unsigned index = 0;
    float path_margin = 3.4028234663852886e+38f;
    for (;;) {
        const tree_node_t *n = &tree_nodes[index];
        if (n->feature == TREE_LEAF) {
            if (n->score == TREE_ABSTAIN)
                return -1;
            if (path_margin < kTreeDecisionMinMargin)
                return -1;
            return n->score;
        }
        float margin = features[n->feature] - n->threshold;
        if (margin < 0.0f)
            margin = -margin;
        if (margin < path_margin)
            path_margin = margin;
        index = (features[n->feature] <= n->threshold) ? (unsigned)n->left : (unsigned)n->right;
    }
}

int tree_predict(const float features[TREE_FEATURE_COUNT])
{
    return tree_predict_score(features) >= 3 ? 1 : 0;
}
