#pragma once

#include <immintrin.h>

#include <array>
#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

class NativeIVF {
 public:
  struct DecisionDebug {
    int fast = -1;
    int out = -1;
    int pre_repair = -1;
    int exact_kd_out = -1;
    int primary_centroid = -1;
    int rh26_final_nprobe = 0;
    bool would_rescore = false;
    bool exact_kd_repaired = false;
    bool rh26_expanded = false;
    bool rh26_repaired = false;
    float quick_best = 0.0f;
    float quick_worst = 0.0f;
    float quick_margin = -1.0f;
    float centroid_gap_max = 0.0f;
    float centroid_gap_last = 0.0f;
    std::array<uint8_t, 5> quick_labels{};
    std::array<float, 5> quick_dists{};
    std::array<uint8_t, 5> rescore_labels{};
    std::array<float, 5> rescore_dists{};
  };

  bool load(const char* path);
  void warmup();
  int classify(const float* q);
  int classify_with_quick_probe(const float* q, int quick_probe_override);
  DecisionDebug classify_debug(const float* q);
  void set_profile(bool enabled) { profile_enabled_ = enabled; }
  void set_trace_label(const char* label, size_t len) {
    trace_label_ = label;
    trace_label_len_ = len;
  }
  void profile_report() const;
  const std::string& error() const { return error_; }

 private:
  static constexpr int kDim = 14;
  static constexpr int kFraudCount = 6;
  static constexpr int kMaxCentroids = 4096;
  static constexpr int kMaxProbe = 512;
  static constexpr int kMaxRepairCandidates = 1024;
  static constexpr int kQuickProbe = 8;
  static constexpr int kExpandedProbe = 20;
  static constexpr int kVectorsPerBlock = 16;
  static constexpr int kBlockStride = kDim * kVectorsPerBlock;
  static constexpr int kRH26VectorsPerBlock = 8;
  static constexpr int kRH26BlockStride = kDim * kRH26VectorsPerBlock;
  static constexpr int kRH26Pairs = kDim / 2;
  static constexpr int8_t kResidual8Padding = 127;
  static constexpr int kBBoxStride = 16;
  static constexpr int kHotBBoxStride = 8;
  static constexpr int kExactKDMaxPartitionCount = 8192;
  static constexpr float kVectorScale = 0.0001f;
  static constexpr float kVectorInvScale = 10000.0f;
  static constexpr float kVectorScaleSq = kVectorScale * kVectorScale;
  static constexpr float kInitialTopDist = 1.0e30f;
  static constexpr size_t kProfileBucketCount = 7;
  static constexpr size_t kMarginProfileBucketCount = 16;

  uint32_t k_ = 0;
  uint32_t total_blocks_ = 0;
  std::vector<float> centroids_;
  std::vector<float> centroid_norms_;
  std::array<float, kDim> vector_scales_{};
  std::array<float, kDim> vector_inv_scales_{};
  std::array<float, kDim> query_scales_{};
  std::array<float, kDim * kDim> query_matrix_{};
  std::vector<uint32_t> offsets_;
  std::vector<uint8_t> labels_;
  std::vector<int16_t> blocks_;
  std::vector<uint16_t> block_label_masks_;
  std::vector<int8_t> cluster_label_pure_;
  std::vector<uint32_t> label_skip_nonzero_offsets_;
  std::vector<uint32_t> label_skip_nonzero_blocks_;
  std::vector<uint32_t> label_skip_notfull_offsets_;
  std::vector<uint32_t> label_skip_notfull_blocks_;
  std::vector<int8_t> residual8_blocks_;
  std::vector<float> residual8_scales_;
  std::vector<int8_t> residual8_filter_blocks_;
  std::vector<float> residual8_filter_scales_;
  std::vector<uint16_t> binary_signatures_;
  std::vector<float> block_min_radii_;
  std::vector<float> block_max_radii_;
  std::vector<float> cluster_max_radii_;
  std::vector<float> cluster_bbox_min_;
  std::vector<float> cluster_bbox_max_;
  std::vector<float> block_bbox_min_;
  std::vector<float> block_bbox_max_;
  std::vector<int16_t> block_hot_min_;
  std::vector<int16_t> block_hot_max_;
  std::vector<float> block_center_;
  std::vector<float> block_center_radius_;
  std::vector<uint16_t> centroid_neighbors_;
  std::vector<uint16_t> local_fraud_graph_;
  std::vector<float> centroid_jl_;
  std::string error_;
  bool rh26_index_ = false;
  uint32_t rh26_groups_ = 0;
  int rh26_nprobe_ = 1;
  int rh26_initial_nprobe_ = 0;
  int rh26_border_nprobe_ = 24;
  int rh26_repair_min_ = 1;
  int rh26_repair_max_ = 4;
  int rh26_repair_candidates_ = 1024;
  int rh26_prefetch_distance_ = 2;
  int rh26_expand_nprobe_ = 0;
  bool rh26_initial_full_policy_enabled_ = false;
  std::array<uint8_t, kMaxCentroids> rh26_initial_full_policy_{};
  bool rh26_repair5_policy_enabled_ = false;
  std::array<uint8_t, kMaxCentroids> rh26_repair5_policy_{};
  float rh26_repair5_skip_q0_min_ = 0.0f;
  bool rh26_repair5_skip_requires_no_expand_ = true;
  bool rh26_repair_select_min_ = false;
  bool rh26_defer_full_top_ = false;
  int rh26_top_pairs_ = kRH26Pairs;
  int rh26_top_candidates_ = 0;
  uint32_t rh26_top_pair_mask_ = 0;
  std::array<uint8_t, kFraudCount * kMaxCentroids> rh26_expand_policy_{};
  std::vector<int16_t> rh26_centroids_;
  std::vector<int16_t> rh26_centroids_psoa_;
  std::vector<int16_t> rh26_bbox_min_;
  std::vector<int16_t> rh26_bbox_max_;
  std::vector<int16_t> rh26_bbox_min_psoa_;
  std::vector<int16_t> rh26_bbox_max_psoa_;
  std::vector<uint32_t> rh26_offsets_;
  std::vector<uint32_t> rh26_counts_;
  std::vector<uint8_t> rh26_labels_;
  std::vector<int16_t> rh26_blocks_;
  bool use_block_bounds_ = true;
  bool use_block_bbox_ = false;
  bool quick_block_bbox_ = false;
  bool rescore_block_bbox_ = false;
  int bbox_dims_ = kBBoxStride;
  bool use_hot_bbox_ = false;
  bool quick_hot_bbox_ = false;
  bool rescore_hot_bbox_ = false;
  int hot_bbox_dims_ = 6;
  bool use_center_bound_ = false;
  bool quick_center_bound_ = false;
  bool rescore_center_bound_ = false;
  int center_bound_dims_ = 6;
  int center_bound_min_from_ = 28;
  bool quick_radius_order_ = false;
  bool quick_dynamic_bounds_ = true;
  bool label_skip_ = false;
  bool label_skip_cached_ = false;
  bool label_skip_cluster_ = false;
  bool label_skip_sparse_ = false;
  bool quick8_label_skip_specialized_ = false;
  bool rescore_label_skip_ = false;
  bool quick_periodic_upper_bound_ = false;
  int quick_periodic_upper_step_ = 8;
  float label_skip_max_worst_ = 0.0f;
  bool prefetch_blocks_ = false;
  bool scan_stage8_ = false;
  bool quick8_specialized_ = false;
  bool dim_hot6_order_ = false;
  bool profile_enabled_ = false;
  bool profile_actual_scan_ = false;
  bool margin_profile_enabled_ = false;
  bool centroid_flip_profile_enabled_ = false;
  bool trace_enabled_ = false;
  bool exact_kd_enabled_ = false;
  bool exact_kd_primary_ = false;
  bool exact_kd_repair_ = false;
  bool exact_kd_repair_policy_enabled_ = false;
  bool exact_kd_repair_feature_policy_enabled_ = false;
  bool exact_kd_partitioned_ = true;
  int exact_kd_partition_count_ = 256;
  int exact_kd_partition_scheme_ = 1;
  int exact_kd_repair_min_ = 1;
  int exact_kd_repair_max_ = 4;
  struct ExactKDRepairRule {
    uint8_t enabled = 0;
    float min_margin = -1.0f;
    float max_worst = 0.0f;
    float min_gap = 0.0f;
    float max_gap = 0.0f;
    float min_last_gap = 0.0f;
    float max_last_gap = 0.0f;
  };
  std::vector<ExactKDRepairRule> exact_kd_repair_policy_;
  std::array<int16_t, 15> exact_kd_amount_cuts_{};
  std::array<int16_t, 6> exact_kd_dow_cuts_{};
  bool rescore_quantized_ = true;
  bool rescore_bounds_ = false;
  bool rescore_specialized_ = false;
  bool scan_scaled_ = false;
  bool rescore_scaled_ = false;
  bool rescore_radius_probes_ = false;
  bool rescore_tail_select_ = false;
  bool rescore_prefilter_select_ = false;
  bool rescore_early_unambig_ = false;
  bool rescore_early_primary_ = true;
  bool rescore_order_lower_bound_ = false;
  bool rescore_block_order_ = false;
  bool rescore_radius_order_ = false;
  bool fused_top_select_ = false;
  bool residual8_index_ = false;
  bool residual8_prefilter_ = false;
  bool residual8_prefilter_quick_label_ = false;
  bool residual8_prefilter_rescore_ = false;
  bool residual8_prefilter_profile_ = false;
  bool residual8_prefilter_policy_enabled_ = false;
  bool residual8_hybrid_repair_ = false;
  bool binary_prefilter_ = false;
  bool binary_prefilter_profile_ = false;
  bool binary_prefilter_policy_enabled_ = false;
  bool per_dim_scale_index_ = false;
  bool query_transform_index_ = false;
  bool query_matrix_index_ = false;
  bool residual8_block_scales_ = false;
  bool residual8_half_scales_ = false;
  bool centroid_graph_rescore_ = false;
  bool centroid_prefilter_ = false;
  bool centroid_jl_prefilter_ = false;
  bool centroid_prefilter_sparse_lanes_ = false;
  bool centroid_prefilter_top_store_only_ = false;
  bool centroid_prefilter_two_pass_ = false;
  bool centroid_dot_distance_ = false;
  bool centroid_rescore_skip_ = false;
  bool rescore_tree_enabled_ = false;
  bool rescore_disabled_ = false;
  bool fast3_approve_rule_ = false;
  bool centroid_flip_dump_ = false;
  bool local_repair_ = false;
  bool local_fraud_graph_enabled_ = false;
  bool rescore234_two_phase_ = false;
  bool remaining_repair_ = false;
  bool remaining_repair_bbox_ = false;
  bool reference_borderline_repair_ = false;
  bool query_borderline_quick_select_ = false;
  bool classsplit_select_ = false;
  int centroid_prefilter_dims_ = 6;
  int centroid_prefilter_probe_ = kExpandedProbe;
  int centroid_jl_dims_ = 6;
  int centroid_jl_candidates_ = 512;
  int quick_probe_ = kQuickProbe;
  int query_obvious_quick_probe_ = kQuickProbe;
  int query_borderline_quick_probe_ = kQuickProbe;
  int expanded_probe_ = kExpandedProbe;
  int rescore_min_ = 2;
  int rescore_max_ = 3;
  int rescore5_probe_ = 0;
  int rescore234_probe_ = 0;
  int rescore234_second_min_ = 2;
  int rescore234_second_max_ = 3;
  int remaining_repair_min_ = 1;
  int remaining_repair_max_ = 4;
  int remaining_repair_candidates_ = 128;
  int rescore_early_min_ = 2;
  int rescore_early_max_ = 3;
  int rescore_early_min_probe_ = 1;
  int second_chance_probe_ = 0;
  int second_chance_min_ = 3;
  int second_chance_max_ = 3;
  int local_repair_window_ = 16;
  int local_repair_min_fast_ = 2;
  int local_repair_max_fast_ = 5;
  int local_fraud_graph_min_fast_ = 0;
  int local_fraud_graph_max_fast_ = 5;
  int centroid_graph_neighbors_ = 16;
  int centroid_graph_seed_count_ = kQuickProbe;
  int centroid_graph_max_probe_ = 28;
  int classsplit_split_ = 0;
  int classsplit_quick_fraud_probes_ = 4;
  int classsplit_rescore_fraud_pct_ = 50;
  int active_dims_ = kDim;
  int residual8_prefilter_dims_ = 6;
  int residual8_filter_dims_ = 6;
  int residual8_hybrid_candidates_ = 128;
  int residual8_hybrid_min_probe_ = 0;
  float residual8_prefilter_slack_ = 2.0f;
  int binary_prefilter_threshold_ = 4;
  std::array<float, 6> rescore_skip_worst_{};
  std::array<float, 6> rescore_skip_margin_{};
  std::array<float, 6> second_chance_min_worst_{};
  std::array<float, 6> second_chance_max_worst_{};
  float rescore5_min_centroid_gap_ = 0.0f;
  float rescore5_min_last_centroid_gap_ = 0.0f;
  float rescore5_max_centroid_gap_ = 0.0f;
  float rescore5_max_last_centroid_gap_ = 0.0f;
  float rescore5_max_best_ = 0.0f;
  float fast3_approve_max_worst_ = 0.03405f;
  float fast3_approve_max_margin_ = -0.03081f;
  struct CentroidRescoreSkipRule {
    uint8_t enabled = 0;
    float min_margin = -1.0f;
    float max_worst = 0.0f;
    float min_gap = 0.0f;
    float max_gap = 0.0f;
    float min_last_gap = 0.0f;
    float max_last_gap = 0.0f;
  };
  std::array<CentroidRescoreSkipRule, 6 * kMaxCentroids> centroid_rescore_skip_policy_{};
  std::array<uint8_t, kMaxCentroids> residual8_prefilter_policy_{};
  std::array<uint8_t, kMaxCentroids> binary_prefilter_policy_{};

  struct ProfileCounters {
    uint64_t calls = 0;
    uint64_t quick_only = 0;
    uint64_t rescore = 0;
    uint64_t rescore_tree = 0;
    uint64_t total_ns = 0;
    uint64_t centroid_ns = 0;
    uint64_t select8_ns = 0;
    uint64_t quick_scan_ns = 0;
    uint64_t select20_ns = 0;
    uint64_t rescore_ns = 0;
    uint64_t max_total_ns = 0;
    uint64_t max_quick_scan_ns = 0;
    uint64_t max_rescore_ns = 0;
    uint64_t quick_probe_blocks = 0;
    uint64_t quick_bound_skipped_blocks = 0;
    uint64_t quick_bound_empty_probes = 0;
    uint64_t quick_dynamic_low_skipped_blocks = 0;
    uint64_t quick_dynamic_high_skipped_blocks = 0;
    uint64_t quick_bbox_checks = 0;
    uint64_t quick_bbox_skipped_blocks = 0;
    uint64_t rescore_bbox_checks = 0;
    uint64_t rescore_bbox_skipped_blocks = 0;
    uint64_t quick_hot_bbox_checks = 0;
    uint64_t quick_hot_bbox_skipped_blocks = 0;
    uint64_t rescore_hot_bbox_checks = 0;
    uint64_t rescore_hot_bbox_skipped_blocks = 0;
  uint64_t quick_center_checks = 0;
  uint64_t quick_center_skipped_blocks = 0;
  uint64_t rescore_center_checks = 0;
  uint64_t rescore_center_skipped_blocks = 0;
  uint64_t quick_label_skipped_blocks = 0;
  uint64_t rescore_label_skipped_blocks = 0;
  uint64_t quick_residual8_checks = 0;
  uint64_t quick_residual8_skipped_blocks = 0;
  uint64_t rescore_residual8_checks = 0;
  uint64_t rescore_residual8_skipped_blocks = 0;
  uint64_t quick_binary_checks = 0;
  uint64_t quick_binary_skipped_blocks = 0;
  uint64_t rescore_binary_checks = 0;
  uint64_t rescore_binary_skipped_blocks = 0;
    uint64_t quick_dynamic_low_events = 0;
    uint64_t quick_dynamic_high_breaks = 0;
    uint64_t quick_blocks_scanned = 0;
    uint64_t quick_stage1_dead_blocks = 0;
    uint64_t quick_stage1_alive_blocks = 0;
    uint64_t quick_stage1_low_dead_halves = 0;
    uint64_t quick_stage1_high_dead_halves = 0;
    uint64_t quick_stage1_both_alive_halves = 0;
    uint64_t quick_stage1_low_lanes = 0;
    uint64_t quick_stage1_high_lanes = 0;
    uint64_t quick_final_dead_blocks = 0;
    uint64_t quick_final_lanes = 0;
    uint64_t quick_top5_accepts = 0;
    uint64_t local_repair_calls = 0;
    uint64_t local_repair_candidates = 0;
    uint64_t local_repair_accepts = 0;
    uint64_t local_repair_fast_changed = 0;
    uint64_t local_fraud_graph_calls = 0;
    uint64_t local_fraud_graph_candidates = 0;
    uint64_t local_fraud_graph_accepts = 0;
    uint64_t local_fraud_graph_fast_changed = 0;
    uint64_t centroid_prefilter_chunks = 0;
    uint64_t centroid_prefilter_full_chunks = 0;
    uint64_t centroid_prefilter_skipped_chunks = 0;
    uint64_t centroid_prefilter_scalar_full = 0;
    uint64_t centroid_prefilter_scalar_skipped = 0;
    uint64_t exact_kd_calls = 0;
    uint64_t exact_kd_ns = 0;
    uint64_t exact_kd_max_ns = 0;
    uint64_t exact_kd_nodes = 0;
    uint64_t exact_kd_leaves = 0;
    uint64_t exact_kd_slots = 0;
    std::array<uint64_t, kProfileBucketCount> total_bins{};
    std::array<uint64_t, kProfileBucketCount> quick_scan_bins{};
    std::array<uint64_t, kProfileBucketCount> rescore_bins{};
    std::array<uint64_t, 6> quick_fraud_counts{};
    std::array<uint64_t, 6> rescore_fraud_counts{};
    std::array<uint64_t, 6> rescore_ns_by_fast{};
    std::array<uint64_t, 6> max_rescore_ns_by_fast{};
    std::array<std::array<uint64_t, 6>, 6> rescore_result_by_fast{};
    std::array<uint64_t, 6> margin_rescore_observed{};
    std::array<uint64_t, 6> margin_rescore_changed{};
    std::array<std::array<uint64_t, kMarginProfileBucketCount>, 6> margin_candidate_skips{};
    std::array<std::array<uint64_t, kMarginProfileBucketCount>, 6> margin_safe_skips{};
    std::array<std::array<uint64_t, kMarginProfileBucketCount>, 6> margin_bad_skips{};
    std::array<uint64_t, kMaxCentroids> centroid_rescore_observed{};
    std::array<uint64_t, kMaxCentroids> centroid_rescore_approval_changed{};
    std::array<uint32_t, 6 * kMaxCentroids> centroid_fast_rescore_observed{};
    std::array<uint32_t, 6 * kMaxCentroids> centroid_fast_rescore_approval_changed{};
    std::array<uint32_t, kMaxCentroids> residual8_probe_checks{};
    std::array<uint32_t, kMaxCentroids> residual8_probe_skipped{};
    std::array<uint32_t, kMaxCentroids> binary_probe_checks{};
    std::array<uint32_t, kMaxCentroids> binary_probe_skipped{};
  };
  ProfileCounters profile_{};

  alignas(32) std::array<float, kMaxCentroids> centroid_dists_{};
  std::array<int, kMaxProbe> probes_{};
  std::array<float, 5> top_dist_{};
  std::array<uint8_t, 5> top_label_{};
  std::array<int, 5> top_slot_{};
  std::array<float, kDim> quantized_{};
  std::array<float, kDim> ordered_query_{};
  std::array<uint16_t, kMaxCentroids> centroid_graph_seen_{};
  uint16_t centroid_graph_epoch_ = 1;
  uint64_t trace_calls_ = 0;
  const char* trace_label_ = nullptr;
  size_t trace_label_len_ = 0;

  struct ExactKDNode {
    std::array<int16_t, kDim> min{};
    std::array<int16_t, kDim> max{};
    int32_t left = -1;
    int32_t right = -1;
    uint32_t start = 0;
    uint32_t count = 0;
  };
  std::vector<uint32_t> exact_kd_slots_;
  std::vector<ExactKDNode> exact_kd_nodes_;
  std::array<int32_t, kExactKDMaxPartitionCount> exact_kd_partition_roots_{};
  std::array<uint32_t, kExactKDMaxPartitionCount> exact_kd_partition_counts_{};
  std::vector<uint16_t> exact_kd_populated_partitions_;
  int exact_kd_leaf_size_ = 256;
  bool exact_kd_leaf_block_simd_ = false;
  int exact_kd_leaf_block_simd_min_lanes_ = 4;

  const float* order_query(const float* q);
  bool query_is_borderline(const float* q) const;
  void centroid_dists(const float* q);
  void centroid_dists_diff(const float* q);
  void centroid_dists_dot(const float* q);
  void centroid_dists_select8(const float* q);
  void centroid_dists_prefilter_select8(const float* q);
  void centroid_dists_prefilter_twopass8(const float* q);
  template <int N>
  void centroid_dists_select_top(const float* q);
  void centroid_dists_select_top_dispatch(const float* q, int n);
  template <int N>
  void centroid_dists_prefilter_target(const float* q);
  void centroid_dists_jl_prefilter_select8(const float* q);
  template <int N>
  void select_top();
  template <int N>
  void select_top_masked();
  void select_classsplit_probes(int n);
  int classsplit_fraud_probe_count(int n) const;
  template <int N>
  void select_top_radius_bound();
  template <int Prefix, int Total>
  void select_tail_after_prefix();
  void select_top20_seeded8();
  void select_top_probes(int n);
  void select_rescore_probes_exact(int n);
  bool can_use_centroid_graph(int n) const;
  bool select_rescore_probes_graph(const float* q, int n);
  bool select_second_chance_probes_graph(const float* q, int from_probe, int to_probe);
  uint16_t next_centroid_graph_epoch();
  void mark_centroid_graph_seen(int idx, uint16_t epoch);
  bool centroid_graph_is_seen(int idx, uint16_t epoch) const;
  void select_rescore_probes(const float* q, int n, bool& full_refreshed);
  bool label_skip_rejects(uint32_t block, int worst) const;
  void select_second_chance_probes(const float* q, int from_probe, int to_probe,
                                   bool& full_refreshed);
  void reset_top();
  void scan_probes(const float* q, int from, int to);
  void scan_probes_residual8(const float* q, int from, int to);
  void scan_quick8_radial(const float* q);
  void scan_quick8_labelskip_radial(const float* q);
  void scan_probes_bounded(const float* q, int from, int to, bool use_bbox);
  void scan_probes_bounded_active_scaled(const float* q, int from, int to);
  void scan_probes_bounded_scaled(const float* q, int from, int to, bool use_bbox);
  void scan_probes_bounded_residual8(const float* q, int from, int to, bool use_bbox);
  void scan_rescore_bounded(const float* q, int from, int to);
  void scan_rescore_bounded_scaled(const float* q, int from, int to);
  void scan_rescore_bounded_scaled_block_ordered(const float* q, int from, int to);
  void scan_rescore_bounded_residual8(const float* q, int from, int to);
  void scan_rescore_residual8_hybrid_repair(const float* q, int from, int to);
  void local_repair_top(const float* q);
  void scan_probes_bounded_profile(const float* q, int from, int to);
  void refresh_selected_centroid_dists(const float* q, int probe_count);
  void ensure_centroid_dists_for(const float* q, int probe_count, bool& full_refreshed);
  void build_centroid_norms();
  bool load_rh26_index(std::ifstream& in);
  void build_rh26_psoa();
  int classify_rh26(const float* q) const;
  void rh26_find_top_centroids(const __m256i* vq, uint32_t* out, int n) const;
  uint32_t rh26_centroid_distance(const __m256i* vq, uint32_t c) const;
  void rh26_scan_cluster(const __m256i* vq, uint32_t c, uint32_t* top_dists,
                         uint8_t* top_labels, uint32_t& max_top) const;
  void rh26_repair(const __m256i* vq, const uint32_t* skip, int nskip,
                   uint32_t* top_dists, uint8_t* top_labels,
                   uint32_t& max_top) const;
  bool rh26_expand_policy_matches(int fast, uint32_t primary_centroid) const;
  void build_centroid_projection();
  float centroid_distance_sq(const float* q, int ci) const;
  float centroid_distance_sq_diff(const float* q, int ci) const;
  float centroid_distance_sq_dot(const float* q, int ci) const;
  void quantize_query(const float* q);
  bool build_exact_kd();
  uint32_t build_exact_kd_node(uint32_t start, uint32_t end);
  int classify_exact_kd(const float* q);
  bool should_exact_kd_repair(int count) const;
  bool should_exact_kd_repair_context(int fast, int count, bool would_rescore,
                                      int primary_centroid, float quick_margin,
                                      float quick_worst, float centroid_gap_max,
                                      float centroid_gap_last) const;
  bool load_exact_kd_repair_policy(const char* path);
  int16_t exact_kd_value(uint32_t slot, int dim) const;
  void build_exact_kd_quantile_cuts();
  uint32_t exact_kd_bucket(int16_t value, const int16_t* cuts, int cut_count) const;
  uint32_t exact_kd_partition_key_from_slot(uint32_t slot) const;
  uint32_t exact_kd_partition_key_from_q16(const std::array<int16_t, kDim>& q16) const;
  int64_t exact_kd_lower_bound(const std::array<int16_t, kDim>& q16,
                               const ExactKDNode& node) const;
  float vector_scale(int dim) const;
  float vector_inv_scale(int dim) const;
  void build_centroid_neighbors();
  bool load_local_fraud_graph(const char* path);
  void build_residual8_prefilter();
  bool residual8_prefilter_rejects(uint32_t block, int probe, const float* q,
                                   float worst_sq) const;
  bool load_residual8_prefilter_policy(const char* path);
  bool residual8_prefilter_enabled_for(int probe) const;
  void record_quick_residual8_prefilter(int probe, bool skipped);
  void record_rescore_residual8_prefilter(int probe, bool skipped);
  void build_binary_signatures();
  uint16_t binary_query_signature(const float* q, int probe) const;
  bool load_binary_prefilter_policy(const char* path);
  bool binary_prefilter_enabled_for(int probe) const;
  int binary_prefilter_threshold_for(int probe) const;
  bool binary_prefilter_rejects(int probe, uint32_t block, uint16_t query_signature,
                                bool quick_call);
  void build_block_radii();
  bool block_slot_is_padding(size_t base, int slot) const;
  float block_value(uint32_t centroid, size_t base, int dim, int slot) const;
  float residual8_scale(uint32_t block, int dim, int probe, int half) const;
  float block_bbox_lower_bound(const float* q, uint32_t block) const;
  float cluster_bbox_lower_bound(const float* q, uint32_t centroid) const;
  float block_hot_bbox_lower_bound(const float* q, uint32_t block) const;
  float block_hot_bbox_lower_bound_scaled(const float* q_scaled, uint32_t block) const;
  float block_center_distance_sq(const float* q8, uint32_t block) const;
  void bound_probe_range(uint32_t& start, uint32_t& end, float center_dist_sq, float worst_dist_sq,
                         float* center_dist_out = nullptr) const;
  uint32_t find_radius_pivot(uint32_t start, uint32_t end, float center_dist) const;
  int count_frauds() const;
  bool top_has_reference_borderline() const;
  void local_fraud_graph_repair_top(const float* q);
  float quick_best_dist() const;
  float quick_worst_dist() const;
  float quick_label_margin(int fast) const;
  float quick_centroid_gap_max() const;
  float quick_centroid_gap(int from_probe) const;
  void trace_quick_decision(uint64_t call, int fast, bool will_rescore) const;
  void trace_second_chance(uint64_t call, int fast, int first_out, bool will_extend,
                           int from_probe, int to_probe) const;
  void trace_final_decision(uint64_t call, int out) const;
  void record_rescore_margin_profile(int fast, int out, float margin);
  void record_rescore_centroid_profile(int primary_centroid, int fast, int out);
  bool should_rescore(int fast, int primary_centroid) const;
  bool fast3_approve_rule_matches(int fast) const;
  bool load_centroid_rescore_skip_policy(const char* path);
  bool centroid_policy_skips_rescore(int fast, int primary_centroid) const;
  int rescore_probe_count(int fast) const;
  int phase_rescore_probe_count(int fast, int full_probe_count) const;
  bool should_rescore234_extend(int fast, int current_probe_count, int full_probe_count,
                                int rescore_result) const;
  bool should_second_chance(int fast, int current_probe_count, int rescore_result) const;
  bool should_remaining_repair(int count, bool full_centroid_dists) const;
  bool rescore_early_unambig_done(int count) const;
  float rescore_probe_lower_bound(int probe) const;
  void scan_rescore_range_linear(const float* q, int from_probe, int to_probe,
                                 bool centroid_dists_ready);
  void scan_rescore_range(const float* q, int from_probe, int to_probe,
                          bool centroid_dists_ready);
  int rescore_quantized_prepared(int probe_count);
  int rescore_quantized_extend_prepared(int from_probe, int to_probe);
  int remaining_repair_prepared(const float* q_scan, int scanned_probe_count,
                                bool full_centroid_dists);
  int rescore_quantized(const float* q, int probe_count);
};
